plugins {
    id 'java-library'
    id 'com.vanniktech.maven.publish' version "0.36.0"
}

project.ext.lwjglVersion = "3.3.3"

switch (org.gradle.internal.os.OperatingSystem.current()) {
    case org.gradle.internal.os.OperatingSystem.LINUX:
        project.ext.lwjglNatives = "natives-linux"
        def osArch = System.getProperty("os.arch")
        if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
            project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
        } else if  (osArch.startsWith("ppc")) {
            project.ext.lwjglNatives += "-ppc64le"
        } else if  (osArch.startsWith("riscv")) {
            project.ext.lwjglNatives += "-riscv64"
        }
        break
    case org.gradle.internal.os.OperatingSystem.MAC_OS:
        project.ext.lwjglNatives = System.getProperty("os.arch").startsWith("aarch64") ? "natives-macos-arm64" : "natives-macos"
        break
    case org.gradle.internal.os.OperatingSystem.WINDOWS:
        def osArch = System.getProperty("os.arch")
        project.ext.lwjglNatives = osArch.contains("64")
                ? "natives-windows${osArch.startsWith("aarch64") ? "-arm64" : ""}"
                : "natives-windows-x86"
        break
}

group = 'io.github.creedvi'
version = '0.5.5'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation fileTree(dir: "native", include: "*.jar")
    implementation("fr.delthas:javamp3:1.0.1")
    implementation("io.github.creedvi:M3D-J:0.1.0a")
    implementation("org.jetbrains:annotations:24.1.0")

    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation("org.lwjgl:lwjgl")
    implementation("org.lwjgl:lwjgl-assimp")
    implementation("org.lwjgl:lwjgl-glfw")
    implementation("org.lwjgl:lwjgl-openal")
    implementation("org.lwjgl:lwjgl-opengl")
    implementation("org.lwjgl:lwjgl-opengles")
    implementation("org.lwjgl:lwjgl-par")
    implementation("org.lwjgl:lwjgl-stb")

    runtimeOnly("org.lwjgl:lwjgl::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-assimp::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-glfw::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-openal::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-opengl::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-opengles::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-par::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-stb::$lwjglNatives")

    // testImplementation("io.github.creedvi:Raygui-J:0.1.0")
}

jar {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.build.dependsOn jar

sourceSets {
    main {
        java.srcDir('src/main')
    }
    test {
        java.srcDir('src/tests')
        resources.srcDir('src/tests/resources')
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
    coordinates(group.toString(), "Raylib-J", version.toString())

    pom {
        name = "Raylib-J"
        description = "Hand-crafted Java binding for the raylib library."
        inceptionYear = "2021"
        url = "https://github.com/CreedVI/Raylib-J"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "CreedVI"
                name = "Calvin Day"
                url = "https://github.com/CreedVI"
            }
        }
        scm {
            url = "https://github.com/CreedVI/Raylib-J/"
            connection = "scm:git:git://github.com/CreedVI/Raylib-J.git"
            developerConnection = "scm:git:ssh://git@github.com/CreedVI/Raylib-J.git"
        }
    }
}